name: Build Purpur 1.20.4
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          cache: gradle
          java-version: 17

      - name: Build Bukkit plugin
        run: ./gradlew :worldedit-bukkit:shadowJar --no-daemon --stacktrace

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: FastAsyncWorldEdit-Bukkit-Purpur-1.20.4
          path: worldedit-bukkit/build/libs/FastAsyncWorldEdit-Bukkit-*.jar
          if-no-files-found: error
